### ISSUE TITLE
dll

### ISSUE THREAD

**Issue by modder780** [FlawTECH/CWissKnife#1]
wheres the dll???

**Comment by FlawTECH** [comment]
You can download it from Thunderstore [here](https://thunderstore.io/c/content-warning/p/FlawTECH/CWissKnife/) (to get the dll click "Manual Download"), but you can also install the mod directly with "Install with Mod Manager" (recommended way).

Optionally, you can also download it directly from the [releases](https://github.com/FlawTECH/CWissKnife/releases) page of this project.
