### ISSUE TITLE
how to install this mod manually?

### ISSUE THREAD

**Issue by jomba1212** [FlawTECH/CWissKnife#5]
when I just download from a site with mods and then transfer this mod to the (plugins) folder and go into the game, then all the functions simply do not work

**Comment by FlawTECH** [comment]
I do not support installation for pirated versions of the game, however I'll be kind enough to provide manual installation steps for paid copies, which should work for offline versions.
As per the [README](https://github.com/FlawTECH/CWissKnife?tab=readme-ov-file#how-to-install), you need to install **both** [BepInExConfigurationManager](https://thunderstore.io/c/content-warning/p/Azumatt/Official_BepInExConfigurationManager/) and this mod. You need to drag **both** mods into your plugins folder.

When in a lobby, you can now press F1 to open the menu
