### ISSUE TITLE
the character barely moves while the mod is on

### ISSUE THREAD

**Issue by kazakhjojo** [FlawTECH/CWissKnife#8]
If I turn on the mod and then enter the game, the character can't move, jump, but can change items and turn on the flashlight for example. It started just recently, I think with the new update. Even when I press the F1 button as usual, it doesn't open the window with mod settings and options. Other mods such as console work just fine. Something minor caught my eye, namely the fact that when I spawn in the room, when I first spawn to the world, I am usually looking straight forward to the mirror, but when I turn on the mod I freeze in a position slightly turned to the left, to the side of the ladder.  If you need video of description of the problem let me know

**Comment by FlawTECH** [comment]
Thank you for opening this issue. It seems in the recent update the developers changed some game properties that broke Configuration Manager and the NoClip algorithm.
I released a new version (1.1.3 - 43f1a56) which you can find in the [Releases page](https://github.com/FlawTECH/CWissKnife/releases/tag/1.1.3) of this project, that should fix all these issues.

Could you try this version and report back if it works for you ? I'll then update the version on ThunderStore.
It seems the developers also moved to Steam Workshop for modding, I'll try and publish a compatible version on there as well in the next few weeks.

**Comment by kazakhjojo** [comment]
Okay, I will try it in couple of days (on Sunday more likely) and will send a feedback here in the comment section 👍

**Comment by kazakhjojo** [comment]
okay, I will try it in couple of days (more likely on Sunday) and send a feedback right here in the comment section 👍

**Comment by kazakhjojo** [comment]
I downloaded the .dll file of the 1.1.3 version, what do I do now, could you guide me through?

**Comment by kazakhjojo** [comment]
The problem is solved! The new version fixed the issue

**Comment by FlawTECH** [comment]
Thank you for testing! I mistakenly pushed the latest version on thunderstore already so you can also update from there.

**Comment by kazakhjojo** [comment]
Oh, I thought I could update it only because I downloaded the .dll file of the 1.1.3 version, well it all worked out in the end
